INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(1,'Friends Food','Fast-food','Gilbert',690287899,'Bonamoussadi',TO_DATE('11/01/2010', 'DD/MM/YYYY'),1);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(2,'5 Fourchettes','Un peu de tout','Albert',672234578,'Bonamoussadi',TO_DATE('01/04/29', 'DD/MM/YYYY'),2);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(3,'Lynk','bar-restaurant','Bernard',699887532,'Bonanjo',TO_DATE('14/05/2010', 'DD/MM/YYYY'),3);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(4,'LA PIZZERIA','PIZZA','Alfredo',650234589,'Bonamoussadi',TO_DATE('23/01/2017', 'DD/MM/YYYY'),4);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(5,'Saga Africa','Mets Africain','Jason',650234589,'Bonamoussadi',TO_DATE('02/03/29', 'DD/MM/YYYY'),5);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(6,'L Italien-Piccola Venezia','Resto Italien','Crispin',699257899,'Yassa',TO_DATE('26/2/2018', 'DD/MM/YYYY'),6);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(7,'Traditional-food','Mets Africain','Stephanie',650245586,'Bonaberi',TO_DATE('08/02/2018', 'DD/MM/YYYY'),7);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(8,'Le Socrate','Un peu de tout','Yvan',675231478,'Mokolo',TO_DATE('09/02/2018', 'DD/MM/YYYY'),8);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(9,'C-PIZZA','PIZZA','Nathan',678962125,'Akwa',TO_DATE('15/07/29', 'DD/MM/YYYY'),9);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(10,'K MyChoice','Fast-food','Maxime',620457896,'Messasi',TO_DATE('21/09/2018', 'DD/MM/YYYY'),10);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(11,'Tchop et Yamo','Fast-food','Calvine',678965423,'Logbessou',TO_DATE('11/05/2018', 'DD/MM/YYYY'),11);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(12,'Hilton','Restaurants-chics','Manuel',699210345,'Bonanjo',TO_DATE('29/06/2018', 'DD/MM/YYYY'),12);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(13,'Restaurant SIM','Mets Traditionnel','Stephane',699621235,'Akwa',TO_DATE('28/02/21', 'DD/MM/YYYY'),13);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(14,'Le plaisir du Gout Pizzeria','PIZZA','Kabhy',678963215,'Kribi',TO_DATE('01/03/2012', 'DD/MM/YYYY'),14);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(15,'Ebene plus','Mets Africain','Nono',690324587,'Kribi',TO_DATE('10/11/2018', 'DD/MM/YYYY'),15);
INSERT INTO Restaurant(id_resto,name_resto,Description,name_employee,phone_number,resto_address,Date_res_created,id_user)VALUES(16,'Pieds dans l eau','aliment marin','Estebane',650321451,'Kribi',TO_DATE('15/11/2018', 'DD/MM/YYYY'),16);

--***********BY TATSINKOU**********--