INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(1, 'Okok','Ceci es un plat de okok',1500,TO_DATE('23/10/2022', 'DD/MM/YYYY'),10,47,3,7,7,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(2, 'Bekwam','Ceci es un plat de bekwam',2500,TO_DATE('15/10/2022', 'DD/MM/YYYY'),20,56,2,14,11,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(3, 'Eru','Ceci es un plat de eru',3000,TO_DATE('17/10/2022', 'DD/MM/YYYY'),15,45,1,15,15,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(4, 'Wrap au jambon','Ceci es un wrap au jambon',1000,TO_DATE('27/10/2022', 'DD/MM/YYYY'),19,30,5,10,8,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(5, 'Brochettes de porc','Une grillade pour les grands et petits',2000,TO_DATE('11/10/2022', 'DD/MM/YYYY'),30,10,6,9,5,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(6, 'Tacos','Ceci es un plat de tacos',2500,TO_DATE('30/10/2022', 'DD/MM/YYYY'),40,9,NULL,NULL,2,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(7, 'Pizza vegetarienne','Une composition de pizza pour ravir les amis des animaux',5500,TO_DATE('05/10/2022', 'DD/MM/YYYY'),20,35,NULL,NULL,4,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(8, 'Big size burger','Une burger normal vous suffit plus? Essayer le big size!',1500,TO_DATE('02/10/2022', 'DD/MM/YYYY'),45,7,2,10,10,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(9, 'Poulet braise','Une envie de découvrir une recette revisité à lafricaine?',4500,TO_DATE('29/09/2022', 'DD/MM/YYYY'),10,20,6,1,15,1);
INSERT INTO Menu(id_menu, Menu_title,Menu_description,Menu_price, Menu_date,Menu_Qty,id_dish,id_seculant,id_complement,id_resto,id_config)VALUES(10, 'Ndole','Ressentez les appels de la côte avec un plat typiquement Duala',1500,TO_DATE('09/09/2022', 'DD/MM/YYYY'),13,44,2,11,13,1);
--*********BY KANGUE*********--