@config

DROP USER FindSW CASCADE;

CREATE USER FindSW IDENTIFIED BY &pass;

PROMPT ALTER USER SET DEFAUT TABLE
ALTER USER FindSW DEFAULT TABLESPACE &tbs
              QUOTA UNLIMITED ON &tbs;

PROMPT ALTER USER GIVE A TEMPORARY TABLESSPACE
ALTER USER FindFood TEMPORARY TABLESPACE &ttbs;

PROMPT GRAND ACESS CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO FindSW
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO FindSW;

PROMPT GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO FindSW
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE , UNLIMITED TABLESPACE TO FindSW;



CONNECT sys/&pass_sys@&connect_string AS SYSDBA;
GRANT execute ON sys.dbms_stats TO FindSW;

REM =======================================================
REM create FindSW schema objects
REM =======================================================
CONNECT FindSW/&pass@&connect_string


