@config

DROP USER FindFood CASCADE;

CREATE USER FindFood IDENTIFIED BY &pass;

PROMPT ALTER USER SET DEFAUT TABLE
ALTER USER FindFood DEFAULT TABLESPACE &tbs
              QUOTA UNLIMITED ON &tbs;

PROMPT ALTER USER GIVE A TEMPORARY TABLESSPACE
ALTER USER FindFood TEMPORARY TABLESPACE &ttbs;

PROMPT GRAND ACESS CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO FindFood
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO FindFood;

PROMPT GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO FindFood
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE , UNLIMITED TABLESPACE TO FindFood;



CONNECT sys/&pass_sys@&connect_string AS SYSDBA;
GRANT execute ON sys.dbms_stats TO FindFood;

REM =======================================================
REM create FindFood schema objects
REM =======================================================
CONNECT FindFood/&pass@&connect_string


