SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 3000
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

CREATE TABLE Users
(
   id_user  INT         NOT NULL,
   username VARCHAR(25) NOT NULL UNIQUE,
   password VARCHAR(9)  NOT NULL,
   id_admin INT
);
 --***********BY TATSINKOU**********--