SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 3000
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

CREATE TABLE Seculant
(
  id_seculant   INT         NOT NULL,
  Name_Seculant VARCHAR(25) NOT NULL
);

 --******BY KANGUE*******--