/***************Table Admin****************/
SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 3000
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF



CREATE TABLE ADMIN (
    id_admin   INT         NOT NULL,
    name_admin VARCHAR(20) NOT NULL,
    pwd_admin  VARCHAR(25) NOT NULL
);
